[general]
import = [
    #"~/.config/alacritty/themes/themes/nvim_dark.toml"
    "~/.config/alacritty/themes/my_nordic.toml"
]

[font]
#normal = { family = "FiraCode Nerd Font", style = "Regular" }
normal = { family = "JetBrainsMono NF SemiBold", style = "Regular" }
